# Generated by Django 6.0.5 on 2026-05-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_extend_upload_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='incapacidad',
            name='dias_empresa',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='incapacidad',
            name='dias_entidad',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
