# Generated by Django 6.0.5 on 2026-05-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_incapacidad_dias_empresa_incapacidad_dias_entidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('SOPORTE', 'Soporte médico'), ('EPICRISIS', 'Epicrisis'), ('FURIPS', 'FURIPS (Accidente Tránsito)'), ('FORMULA', 'Fórmula médica'), ('CARTA', 'Carta / Comunicación'), ('LIQUIDACION', 'Liquidación'), ('OTRO', 'Otro')], default='SOPORTE', max_length=20),
        ),
    ]
