# Generated by Django 6.0.5 on 2026-05-14 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_documento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='eps',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message='El nombre de la EPS debe contener solo letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')], verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='numero_identificacion',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='El número de identificación debe contener solo números.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='incapacidad',
            name='entidad_responsable',
            field=models.CharField(choices=[('EPS', 'EPS'), ('ARL', 'ARL'), ('OTRO', 'Otro')], default='EPS', max_length=20),
        ),
        migrations.AlterField(
            model_name='tipoincapacidad',
            name='entidad_responsable',
            field=models.CharField(choices=[('EPS', 'EPS'), ('ARL', 'ARL'), ('OTRO', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tipoincapacidad',
            name='nombre',
            field=models.CharField(max_length=120, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre debe contener solo letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')]),
        ),
    ]
