# Generated by Django 6.0.5 on 2026-05-14 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_colaborador_eps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incapacidad',
            name='prorroga_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siguientes', to='gestion.incapacidad', verbose_name='Prórroga de'),
        ),
    ]
